# -*- coding: utf-8 -*-
"""Server panas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iI1PBUfo9SBArEan9E1c5ryuSSf3LHjH

```
███╗   ███╗██╗███╗   ██╗███████╗ ██████╗ ██████╗ ██╗      █████╗ ██████╗
████╗ ████║██║████╗  ██║██╔════╝██╔════╝██╔═══██╗██║     ██╔══██╗██╔══██╗
██╔████╔██║██║██╔██╗ ██║█████╗  ██║     ██║   ██║██║     ███████║██████╔╝
██║╚██╔╝██║██║██║╚██╗██║██╔══╝  ██║     ██║   ██║██║     ██╔══██║██╔══██╗
██║ ╚═╝ ██║██║██║ ╚████║███████╗╚██████╗╚██████╔╝███████╗██║  ██║██████╔╝
╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝
```
**Crea un Servidor de Minecraft en Google Colab! (Versión Modificada por SoyMichas y en Español)**

---

El Script de abajo hará que tu servidor se inicie. Primero tendrás que crear el servidor para poder usarlo - no te preocupes, los scripts de abajo harán la gran mayoría del trabajo para ti. A lo mejor quieres cambiar la región del servidor, revisa abajo.

Original: https://github.com/thecoder-001/MineColab

# **1º Paso -> Crear-el-servidor (Solo hacer la primera vez)**

El codigo de abajo creará tu servidor y aceptará el EULA. Cuando uses estos scripts, Tu servidor estará listo para iniciarse.

**Descargar el Servidor de Minecraft**

El codigo de abajo descargará Paper, un tipo de servidor Vanilla de alto rendimiento el cual permite utilizar plugins.
Si quieres usar otro tipo de server.jar ponlo en la carpeta Drive manualmente.

- Los archivos del servidor estarán guardados en tu Google Drive (Los de la cuenta de Google que elijas o estes usando)
"""

# Commented out IPython magic to ensure Python compatibility.
# Cambia "1.20.2" con la version que desees.
# Available tested versions / Versiones disponibles testeadas:
# - 1.20.2
# - 1.20.1
# - 1.20
# - 1.19.4
# - 1.19.3
# - 1.19.2
# - 1.19.1
# - 1.19
# - 1.18.2
# - 1.18.1
# - 1.18
# - 1.17.1
# - 1.17
# - 1.16.5
# - 1.16.4
# - 1.16.3
# - 1.15.2
# - 1.14.4
# - 1.13.2
# - 1.12.2
# - 1.11.2
# - 1.10.2
# - 1.9.4
# - 1.8.8
# Newer versions might work too, however this isn't guaranteed. / Las nuevas versiones deberían funcionar, pero no es garantizado.
version = '1.20.1'

#Chose server type. Currently available versions:
# - paper (Lo más vanilla. Es lo mismo que SPIGOT, bukkit, etc)
# - forge (Para usar MODS. Es básicamente FORGE) [Aviso, la instalación tarda APROX 10-15 min, al ejecutar el primer paso, esperar a que ponga COMPLETADO]
# - fabric (Para jugar Fabric. Es una alternativa a Forge)
# - vanilla (Minecraft Vanilla sin mods ni plugins)
# - snapshot (En "version" tendrás que poner el nombre de la SNAPSHOT, EJ: 23w42a)

server_type = 'forge'

# Print experimental build warning -- no longer needed
# if version == '1.18' and server_type == 'paper':
#  print("<!> Paper 1.18 builds are still experimental. Make regular Backups!")

from google.colab import drive
import requests
import json


drive.mount('/content/drive')

# Create the directory which will be used for the server
! mkdir "/content/drive/My Drive/Minecraft-server"
# %cd "/content/drive/My Drive/Minecraft-server"

# Internal init...

if server_type == 'paper':
  a = requests.get("https://papermc.io/api/v2/projects/paper/versions/" + version)
  #print(a.json()["builds"][-1])
  b = requests.get("https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]))
  #print(b.json()["downloads"]["application"]["name"])
  print("https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]) + "/downloads/" + b.json()["downloads"]["application"]["name"])
  serverURL = "https://papermc.io/api/v2/projects/paper/versions/" + version + "/builds/" + str(a.json()["builds"][-1]) + "/downloads/" + b.json()["downloads"]["application"]["name"]

if server_type == 'forge':
  serverURL = "https://serverjars.com/api/fetchJar/modded/forge/" + version

if server_type == 'vanilla':
  serverURL = "https://serverjars.com/api/fetchJar/vanilla/vanilla/" + version

if server_type == 'snapshot':
  serverURL = "https://serverjars.com/api/fetchJar/vanilla/snapshot/" + version

if server_type == 'fabric':
  serverURL = 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.11.2/fabric-installer-0.11.2.jar'

if server_type == 'mohist':
  serverURL = "https://serverjars.com/api/fetchJar/modded/mohist/" + version

jar_name = {'paper': 'server.jar', 'fabric': 'fabric-installer.jar', 'forge': 'forge.jar', 'vanilla': 'vanilla.jar', 'snapshot': "snapshot.jar", 'mohist' : "mohist.jar"}

print('Descargando a Google Drive...')

r = requests.get(serverURL)

if r.status_code == 200:
  with open('/content/drive/My Drive/Minecraft-server/' + jar_name[server_type], 'wb') as f:
    f.write(r.content)
else:
  print('Error '+ str(r.status_code) + '! La versión que has elegido probablemente no funciona / Most likely you entered a unsupported version. Try running the code again if you think that shouldn\'t have happened.')

# Running specific install path.
if server_type == 'fabric':
  !java -jar fabric-installer.jar server -mcversion $version -downloadMinecraft

if server_type == 'forge':
#   %cd "/content/drive/My Drive/Minecraft-server"
  !java -jar forge.jar --installServer

# Saving config
colabconfig = {"server_type": server_type,
               "server_version": version}
json.dump(colabconfig, open("colabconfig.json",'w'))

print('Completado!') # todo: Would show even after erroring.

# Please read the file stored in your server folder before running this command.
# Also, go to https://www.minecraft.net/en-us/eula to read Minecraft's EULA.

# Make sure Drive is mounted
from google.colab import drive
drive.mount('/content/drive')

# %cd "/content/drive/My Drive/Minecraft-server"
!echo "eula=true" >> eula.txt

"""# **-> Iniciar el servidor de Minecraft - Usar esto siempre que quieras abrirlo**

**IMPORTANTE:**
- Para poner un comando por consola, lo puedes hacer por aquí. Básicamente esto de abajo será tu consola (donde pondrás comandos y verás los logs)
- Es recomendable tener la pestaña de Google Colab abierta para que el servidor no se cierre, es posible que cada cierto tiempo te pida que resuelvas un captcha.

  **Si usas NGROK:**
  - La IP cambiará siempre que reinicies el servidor.
  - Tienes que poner el TOKEN de Ngrok abajo, entra en este link https://dashboard.ngrok.com/auth para obtener tu token (tienes que tener una cuenta creada en ngrok)
  - Puedes cambiar en este codigo más abajo la REGIÓN, esto es importante para el LAG y PING. Usa las regiones más cercanas a ti. La región predeterminada es Estados Unidos, la cuál no es recomendada para paises de America del sur o España. Para estos se pueden usar regiones como 'sa' (Brasil) y 'eu' (Europa). Puedes cambiarlo en este código de abajo donde esta señalado.
  
  **Si usas PLAYIT:**
  - Tienes que darle click al link que aparecerá, ahí tendrás que crear un tunnel para Minecraft y usar la IP que te dará la aplicación.
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import re
import json
import glob

# Update the package lists
!sudo apt update &>/dev/null && echo "apt cache successfully updated" || echo "apt cache update failed, you might receive stale packages"

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
# Change directory to the Minecraft server folder on Google Drive
# %cd "/content/drive/My Drive/Minecraft-server"
!ls #list the directory contents (to verify that working directory was changed)

# Import config file.
if os.path.isfile("colabconfig.json"):
  colabconfig = json.load(open("colabconfig.json"))
else:
  colabconfig = {"server_type": "generic"} # using default, if config doesn't exists.
  json.dump(colabconfig, open("colabconfig.json",'w'))

# Install OpenJDK
# !wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
# !sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ &>/dev/null || echo "Failed to add repo. Still can be ignored if openjdk17 gets installed."
version = colabconfig["server_version"]
if colabconfig["server_version"] < "1.17":
  !sudo apt-get purge openjdk* > /dev/null 2>&1
  !sudo apt-get install openjdk-8-jre-headless &>/dev/null && echo "Yay! Openjdk8 has been successfully installed." || echo "Failed to install OpenJdk8."
else:
  !sudo apt-get purge openjdk* > /dev/null 2>&1
  !sudo apt-get install openjdk-17-jre-headless &>/dev/null && echo "Yay! Openjdk17 has been successfully installed." || echo "Failed to install OpenJdk17."

#Perform java version check
java_ver = !java -version 2>&1 | awk -F[\"\.] -v OFS=. 'NR==1{print $2}'
if java_ver[0] == "17" :
  print("Se esta utilizando JAVA 17 - You are using JAVA 17.")
else:
  print("Estas utilizando una versión inferior a JAVA 17: ", java_ver[0], ". You are using a downgraded java version. Minecraft 1.17+ might not work.")

# Server jar names.
jar_list = {'paper': 'server.jar', 'fabric': 'fabric-server-launch.jar', 'generic': 'server.jar', 'forge': 'run.bat', 'vanilla': 'vanilla.jar', 'snapshot': 'snapshot.jar', 'mohist': 'mohist.jar'}
jar_name = jar_list[colabconfig["server_type"]]

# Java arguments.
if colabconfig["server_type"] == "paper":
  server_flags = "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
else:
  server_flags = "" # aiker's flags might negatively impact performance on non-paper servers.
memory_allocation = "-Xms8704M -Xmx8704M"

# Chose the tunnle service you want to use
# Available options: ngrok, playit
tunnel_service = "playit" # Si prefieres usar NGROK cámbialo aquí <--------
print("Usando", tunnel_service)

if tunnel_service == "ngrok":
  !pip -q install pyngrok
  from pyngrok import conf, ngrok

  # Ask for the ngrok authtoken
  print("Consigue tu authtoken de https://dashboard.ngrok.com/auth")
  import getpass

  # v - - - - - - - TOKEN  - - - - - - - v

  authtoken = ""  # <---- TOKEN NGROK (PON AQUÍ TU TOKEN [TIENE QUE ESTAR ENTRE LAS "COMILLAS"])

  ! ngrok authtoken $authtoken # login to ngrok

  # Sets default ngrok region

  # v - - - - - - - REGIONES DISPONIBLES  - - - - - - - v

  # ap - Asia/Pacific (Singapore)
  # au - Australia (Sydney)
  # eu - Europa (Frankfurt - Alemania)
  # in - India (Mumbai)
  # jp - Japan (Tokyo)
  # sa - America del sur (São Paulo - Brasil)
  # us - United States (Ohio)
  conf.get_default().region = 'us'  # <--- Cambia esto por la region que quieras (solo ngrok)

  # ^ - - - - - - - REGIONES DISPONIBLES  - - - - - - - ^

  # Connect to ngrok
  url = ngrok.connect(25565, 'tcp')
  print('La IP de tu servidor es ' + ((str(url).split('"')[1::2])[0]).replace('tcp://', ''))

elif tunnel_service == "playit":
  ! curl -SsL https://playit-cloud.github.io/ppa/key.gpg | sudo apt-key add -
  ! sudo curl -SsL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list
  print('Iniciando servidor...')
  ! sudo apt update &>/dev/null && sudo apt install playit &>/dev/null && echo "Playit.gg instalado" || echo "Error al instalar playit"
  if colabconfig["server_type"] == "forge":
    version = colabconfig["server_version"]
    if colabconfig["server_version"] < "1.17":
      oldpathtoforge = glob.glob(f"/content/drive/My Drive/Minecraft-server/forge-{version}-*.jar")
      if oldpathtoforge:  # Check if the list is not empty
        path = oldpathtoforge[0]  # Get the first path from the list
        print(path)
        ! playit & java $memory_allocation -jar "{path}" nogui
      else:
        print("No forge universal jar found.")
    else:
      pathtoforge = glob.glob(f"/content/drive/My Drive/Minecraft-server/libraries/net/minecraftforge/forge/{version}-*/unix_*.txt")
      if pathtoforge:  # Check if the list is not empty
        path = pathtoforge[0]  # Get the first path from the list
        print(path)
        ! playit & java @user_jvm_args.txt "@{path}" "$@"
      else:
        print("No unix_args.txt found.")
  else:
    ! playit & java $memory_allocation $server_flags -jar $jar_name nogui

print('Iniciando servidor...')

if colabconfig["server_type"] == "forge":
  version = colabconfig["server_version"]
  if colabconfig["server_version"] < "1.17":
    oldpathtoforge = glob.glob(f"/content/drive/My Drive/Minecraft-server/forge-{version}-*.jar")
    if oldpathtoforge:  # Check if the list is not empty
      path = oldpathtoforge[0]  # Get the first path from the list
      print(path)
      !java $memory_allocation -jar "{path}" nogui
    else:
      print("No forge universal jar found.")
  else:
    pathtoforge = glob.glob(f"/content/drive/My Drive/Minecraft-server/libraries/net/minecraftforge/forge/{version}-*/unix_*.txt")
    if pathtoforge:  # Check if the list is not empty
      path = pathtoforge[0]  # Get the first path from the list
      print(path)
      !java @user_jvm_args.txt "@{path}" "$@"
    else:
      print("No unix_args.txt found.")
else:
 !java $memory_allocation $server_flags -jar $jar_name nogui

"""**FAQ - COSAS QUE TIENES QUE SABER**

Google Colab no esta pensado para crear servidores de Minecraft, pero se pueden hacer. Google Colab promete funcionar 12 horas seguidas, sin embargo es posible que se cierre si no hay una persona que este revisando la página o usando la consola, basicamente si la página detecta inactividad el proceso terminará. El rendimiento es de 12 GB de RAM aproximadamente, junto con un procesador con una potencia de 2.2 GHz y 2 theards, esto es mejor que muchos hostings de pago, pero no tiene soporte y no promete estar abierto siempre, se pueden poner mods, pero no es recomendable saturarlo con muchos al igual que plugins, lo que más limita a este servidor es su procesador el cuál, no es muy bueno, cualquier hosting por 12 USD puede ofrecerte un servidor de mayor calidad, si tienes pensado crear algo para muchos usuarios, es mucho mejor eso. Los servidores utilizados son los de Google junto con el proxy de Ngrok.

"""